name: FB Ads Hygiene Daily

on:
  workflow_dispatch: # Тепер тригериться зовнішнім cron-job.org

jobs:
  run-hygiene:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run FB Hygiene Script
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PYTHONUNBUFFERED: "1"
        run: python fb_hygiene.py
